name: Publish to Nuget
on:
  workflow_dispatch:

jobs:
  publish:
    env:
      SOLUTION: 'GoLive.Generator.ApiClientGenerator/GoLive.Generator.ApiClientGenerator.csproj'
      BUILD_VER: '3.1'
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{secrets.NUGET_KEY}}
      - name: Get Build Version
        run: |
          echo "BUILD_VERSION=${{ format('{0}.{1}', env.BUILD_VER, github.run_number ) }}" >> $env:GITHUB_ENV
      - name: Build
        run: dotnet pack $SOLUTION --configuration Release -p:Version=$env:BUILD_VERSION -p:PackageVersion=$env:BUILD_VERSION -p:GeneratePackageOnBuild=false
      - name: Publish
        run: nuget push **/*.nupkg
